code --install-extension vsmobile.vscode-react-native
code --install-extension flowtype.flow-for-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension RobinMalfait.prettier-eslint-vscode
code --install-extension ms-vscode.atom-keybindings
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension naumovs.color-highlight
code --install-extension joelday.docthis
code --install-extension waderyan.gitblame
code --install-extension donjayamanne.git-extension-pack
code --install-extension christian-kohler.path-intellisense
code --install-extension 2gua.rainbow-brackets
code --install-extension EQuimper.react-native-react-redux
code --install-extension cssho.vscode-svgviewer
code --install-extension wayou.vscode-todo-highlight
code --install-extension teabyii.ayu
code --install-extension Poorchop.theme-darktooth
code --install-extension joshpeng.theme-onedark-sublime
code --install-extension shakram02.bash-beautify